### ISSUE TITLE
vue/demo cannot run

### ISSUE THREAD

**Issue by jojoname** [microsoft/powerbi-client-vue-js#6]
vue/demo

npm run demo
error message  Uncaught SyntaxError: Unexpected token .    App.vue:48

 How to modify it to run

**Comment by jojoname** [comment]
> vue/demo
> 
> npm 运行演示错误消息未捕获语法错误：意外令牌 。应用：48
> 
> 如何修改它以运行

OK
Demo can only be run in Edge browser

**Comment by bapat-atharva** [comment]
Not sure why you are getting the error, we are able to run the demo in Edge, Chrome, Firefox. Please let us know if you have any additional details.

**Comment by 470772345** [comment]
![image](https://user-images.githubusercontent.com/19266094/230553851-1c093aff-b91c-41b8-8f57-5f060dace6fe.png)

After clone this rep, npm install , npm run demo ,but  run some wrong; ?

**Comment by KotanaSai21** [comment]
@470772345 , It seems,  `powerbi-client-vue-js` package is not installed.

If you're inside the vue folder, Try these commands to run the demo app.
```
npm run install:demo
npm run demo
```

If you're inside the demo folder, Try these commands to run the demo app.
```
npm i
npm run demo
```

Feel free to reach out to us, if you have any other queries.

**Comment by 470772345** [comment]
> @470772345 , It seems, `powerbi-client-vue-js` package is not installed.
> 
> If you're inside the vue folder, Try these commands to run the demo app.
> 
> ```
> npm run install:demo
> npm run demo
> ```
> 
> If you're inside the demo folder, Try these commands to run the demo app.
> 
> ```
> npm i
> npm run demo
> ```
> 
> Feel free to reach out to us, if you have any other queries.

Thanks for your help， it's already good。

**Comment by 470772345** [comment]
Hello, currently I embed a PowerBIReportEmbed for each menu page, when I switch menus, I use cache for each page, <keepalive>but it triggers an update every time, is there a configuration can it not trigger every time

**Comment by v-MadhavC** [comment]
When embedding multiple reports, it's recommended to use the same iFrame for each report instead of creating a new iFrame each time. You should use powerbi.embed(element, config) with different configurations to replace the previous report. 
For more details you can refer to this documentation: [Best practices for faster performance in Power BI embedded analytics - Power BI | Microsoft Learn](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-performance-best-practices#switching-between-reports)

To better understand the  issue, could you provide what you are caching and what specifically triggers the update? Are there specific calls or re-renders occurring?

**Comment by v-MadhavC** [comment]
We are waiting for your response. If no response is received within the next couple of weeks, the issue will be closed.

**Comment by ayeshurun** [comment]
The issue is closed since no response was received.
